[package]
name = "complex-learned-controls"
version = "0.1.0"
authors = ["Alice Cecile <alice.i.cecile@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "3adcba9461f79e7f63fb190e9606f522e9ab95cd" }
bevy-tick-timers = "0.1.1"